# Generated by Django 4.0.3 on 2022-04-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_message_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='mark',
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
